### ISSUE TITLE
Laravel only?

### ISSUE THREAD

**Issue by tuupola** [rocketeers/rocketeer-slack#15]
Looking at the code it seems this is Laravel only? Did I understand correctly?

**Comment by n0ts** [comment]
It's 'No'

**Comment by tuupola** [comment]
Ok. Is there any docs how to setup the Slack notification with non-Laravel projects?

**Comment by tuupola** [comment]
Anyone else searching for usage without Laravel, the steps are following.

```
$ rocketeer plugin:install anahkiasen/rocketeer-slack
$ rocketeer plugin:config anahkiasen/rocketeer-slack
$ nano -w .rocketeer/plugins/rocketeers/rocketeer-slack/config.php 
```

**Comment by n0ts** [comment]
:+1:
