### ISSUE TITLE
don't install illuminate/support v4.2.1|don't install laravel/framework v5.4.0

### ISSUE THREAD

**Issue by mvpoorna** [rocketeers/rocketeer-slack#31]
This is not working with laravel 5.4 can you suggest me the solution for this.

**Comment by mvpoorna** [comment]
@Anahkiasen @rauanmayemir @tuupola @mcrumm @bramdevries  can you people help me in this issue ???

Thanks in advance..!

**Comment by Anahkiasen** [comment]
You can use the standalone PHAR to avoid dependencies conflicts. This is not solvable at the moment without a new breaking release as it would imply updating most dependencies of the project which would cause major breakage and require quite some internal updates :/
